### ISSUE TITLE
Missing function mdiag.m

### ISSUE THREAD

**Issue by hensomc** [flavioluiz/AeroFlex#11]
I am interested in this work but able to run the examples...

The examples fail during execution because of a missing file "mdiag.m".  Can you please add that to the repo?

Thanks

Run time message:
Undefined function 'mdiag' for input arguments of type 'double'.
Error in Airplane (line 84)
                Me = mdiag(Me, getmemberMe(members{i}));

**Comment by flavioluiz** [comment]
Hi! thank you for your message!

I've just checked, and actually "mdiag.m" is from the Matlab Robust Control Toolbox. Indeed, it does the samething as "blkdiag.m", so I've just  sent a commit to use "blkdiag" and it seems to work.

Best regards,
Flavio
